- hosts: all
  tasks:
    - name: Install HTTPD on Red Hat
      package:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start HTTPD service on Red Hat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Update apt cache on Debian
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache2 on Debian
      package:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Start Apache2 service on Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Create index.html with content
      copy:
        content: "hello from ansible"
        dest: /var/www/html/index.html
      when: ansible_facts['os_family'] in ["RedHat", "Debian"]
